"""
TaxPay Guard - PDF Certificate Generator
Generates Due Diligence Certificates using FPDF2 (Pure Python)
"""
import os
import io
import datetime
from fpdf import FPDF
from fpdf.enums import XPos, YPos

try:
    import qrcode
    HAS_QRCODE = True
except ImportError:
    HAS_QRCODE = False
    print("Warning: qrcode library not installed.")

# Constants for layout
MARGIN = 15
PAGE_WIDTH = 210
PAGE_HEIGHT = 297
CONTENT_WIDTH = PAGE_WIDTH - (2 * MARGIN)

class CertificatePDF(FPDF):
    def header(self):
        # Logo placeholder (TaxPay Guard)
        self.set_font("helvetica", "B", 24)
        self.set_text_color(37, 99, 235) # Blue-600
        self.cell(0, 10, "ITC Shield", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="L")
        
        self.set_font("helvetica", "", 10)
        self.set_text_color(107, 114, 128) # Gray-500
        self.cell(0, 5, "Vendor Compliance & Due Diligence Certificate", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="L")
        
        self.ln(10)
        
    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(156, 163, 175) # Gray-400
        self.cell(0, 10, f"Generated by ITC Shield on {datetime.datetime.now().strftime('%d %b %Y, %I:%M %p')}", align="C")

def generate_qr_code(data: str) -> io.BytesIO:
    """Generate QR code as BytesIO stream"""
    if not HAS_QRCODE:
        return None
    
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=10,
        border=2,
    )
    qr.add_data(data)
    qr.make(fit=True)
    
    img = qr.make_image(fill_color="#1e40af", back_color="white")
    
    buffer = io.BytesIO()
    img.save(buffer, format='PNG')
    buffer.seek(0)
    return buffer

def generate_certificate(check_data: dict) -> bytes:
    """
    Generate PDF certificate using FPDF2.
    Wraps internal generation to catch errors.
    """
    try:
        pdf_output = _generate_certificate_internal(check_data)
        return bytes(pdf_output)
    except Exception as e:
        import traceback
        # Log payload and traceback for debugging
        with open("/tmp/pdf_error.log", "w") as f:
            f.write(f"Timestamp: {datetime.datetime.now()}\n")
            f.write(f"Data Payload: {str(check_data)}\n")
            f.write("-" * 50 + "\n")
            f.write(traceback.format_exc())
            
        print(f"Error generating PDF: {e}")
        
        # Return a simple text PDF with error message as fallback
        try:
            pdf = FPDF()
            pdf.add_page()
            pdf.set_font("helvetica", "B", 12)
            pdf.cell(0, 10, "Error Generating Certificate", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_font("helvetica", "", 10)
            pdf.multi_cell(0, 10, f"We encountered an error while generating this certificate.\n\nError Details: {str(e)}\n\nPlease contact support with this error message.")
            return bytes(pdf.output())
        except:
            return b"Error generating PDF certificate (Critical Failure)"

def _generate_certificate_internal(check_data: dict) -> bytes:
    pdf = CertificatePDF()
    pdf.add_page()
    pdf.set_margin(MARGIN)
    
    # --- Check Details Box ---
    pdf.set_fill_color(249, 250, 251) # Gray-50
    pdf.rect(x=MARGIN, y=pdf.get_y(), w=CONTENT_WIDTH, h=45, style="F")
    
    # Vendor Name & GSTIN
    pdf.set_y(pdf.get_y() + 5)
    pdf.set_font("helvetica", "B", 16)
    pdf.set_text_color(17, 24, 39) # Gray-900
    pdf.cell(CONTENT_WIDTH - 40, 10, str(check_data.get('vendor_name', 'N/A'))[:40], new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.set_font("helvetica", "", 12)
    pdf.set_text_color(55, 65, 81) # Gray-700
    pdf.cell(100, 8, f"GSTIN: {check_data.get('gstin', 'N/A')}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.set_font("helvetica", "", 10) 
    pdf.cell(100, 6, f"Check ID: {check_data.get('check_id', 'N/A')}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    # Format timestamp nicely
    timestamp = check_data.get('timestamp', datetime.datetime.now())
    if isinstance(timestamp, str):
        try:
            # Parse ISO format timestamp
            timestamp = datetime.datetime.fromisoformat(timestamp.replace('Z', '+00:00'))
        except:
            timestamp = datetime.datetime.now()
    
    formatted_date = timestamp.strftime('%d %b %Y, %I:%M %p')
    pdf.cell(100, 6, f"Date: {formatted_date}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # --- QR Code (Top Right) ---
    if HAS_QRCODE and 'check_id' in check_data:
        verification_url = f"https://taxpayguard.in/verify?id={check_data['check_id']}&gstin={check_data.get('gstin')}"
        qr_img = generate_qr_code(verification_url)
        if qr_img:
            # Place QR code at top right of the gray box
            pdf.image(qr_img, x=PAGE_WIDTH - MARGIN - 35, y=35, w=30)

    pdf.ln(10)

    # --- Decision Status ---
    decision = check_data.get('decision', 'UNKNOWN')
    
    # Status Colors
    if decision == 'RELEASE':
        bg_color = (220, 252, 231) # Green-100
        text_color = (22, 101, 52) # Green-800
        status_text = "PASSED - PAYMENT APPROVED"
    elif decision == 'HOLD':
        bg_color = (254, 243, 199) # Yellow-100
        text_color = (146, 64, 14) # Yellow-800
        status_text = "WARNING - REVIEW REQUIRED"
    else: # STOP
        bg_color = (254, 226, 226) # Red-100
        text_color = (153, 27, 27) # Red-800
        status_text = "FAILED - DO NOT PAY"
        
    pdf.set_fill_color(*bg_color)
    pdf.set_draw_color(*text_color)
    pdf.set_line_width(0.5)
    
    # Status Banner
    pdf.rect(x=MARGIN, y=pdf.get_y(), w=CONTENT_WIDTH, h=15, style="FD")
    
    pdf.set_y(pdf.get_y() + 3)
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(*text_color)
    pdf.cell(CONTENT_WIDTH, 10, status_text, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.ln(10)
    
    # --- Details Section ---
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Compliance Details", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(55, 65, 81)
    
    # Helper to draw row with text wrapping
    def draw_row(label, value):
        pdf.set_font("helvetica", "B", 10)
        
        # Calculate height required for value
        pdf.set_font("helvetica", "", 10)
        # multi_cell height calculation simulation
        # cell width is CONTENT_WIDTH - 50
        val_width = CONTENT_WIDTH - 50
        
        # Split text into lines
        words = str(value).split(' ')
        lines = []
        current_line = []
        
        for word in words:
            test_line = ' '.join(current_line + [word])
            if pdf.get_string_width(test_line) < val_width - 4: # -4 for padding
                current_line.append(word)
            else:
                lines.append(' '.join(current_line))
                current_line = [word]
        lines.append(' '.join(current_line))
        
        line_height = 6
        total_height = max(8, len(lines) * line_height + 4) # +4 for padding
        
        # Draw Label Cell
        start_x = pdf.get_x()
        start_y = pdf.get_y()
        
        pdf.set_font("helvetica", "B", 10)
        pdf.cell(50, total_height, label, border=1)
        
        # Draw Value Cell
        pdf.set_xy(start_x + 50, start_y)
        pdf.set_font("helvetica", "", 10)
        
        # Save X and Y for border rect
        val_start_x = pdf.get_x()
        val_start_y = pdf.get_y()
        
        # Draw text using multi_cell
        # We need to center slightly vertically if single line, but simple multi_cell starting at top with padding is fine
        pdf.set_xy(val_start_x, val_start_y + 2) # Top padding
        pdf.multi_cell(val_width, line_height, str(value), border=0, align='L')
        
        # Draw border around value cell
        pdf.set_xy(val_start_x, val_start_y)
        pdf.rect(val_start_x, val_start_y, val_width, total_height)
        
        # Move cursor to next line
        pdf.set_xy(MARGIN, start_y + total_height)

    draw_row("Risk Level", check_data.get('risk_level', 'N/A'))
    draw_row("Reason", check_data.get('decision_reason', check_data.get('reason', 'N/A')))
    draw_row("Rule ID", check_data.get('rule_id', 'N/A'))
    draw_row("Amount Check", f"INR {check_data.get('amount', '0')}")
    draw_row("Rule 37A Status", check_data.get('rule_37a_status', 'Not Verified'))
    
    pdf.ln(10)
    
    # --- Filing History ---
    filing_history = check_data.get('filing_history', [])
    if filing_history:
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, "Recent Filing History", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
        # Table Header
        pdf.set_fill_color(243, 244, 246)
        pdf.set_font("helvetica", "B", 9)
        pdf.cell(40, 8, "Period (FY)", border=1, fill=True)
        pdf.cell(40, 8, "Month", border=1, fill=True) # Changed from Tax Period
        pdf.cell(40, 8, "Type", border=1, fill=True)
        pdf.cell(30, 8, "Status", border=1, fill=True)
        pdf.cell(30, 8, "Date", border=1, fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
        # Table Rows
        pdf.set_font("helvetica", "", 9)
        for filing in filing_history[:10]: # Limit to 10 entries
            # Handle different keys from different data sources (GSP vs Mock)
            
            # 1. Financial Year & Month
            period = filing.get('period', filing.get('tax_period', '-'))
            fy = filing.get('financial_year', '-')
            month_name = "-"
            
            # Extract from "MM/YYYY" format (e.g. 02/2025)
            if "/" in str(period) and len(str(period)) == 7:
                try:
                    m, y = str(period).split("/")
                    month_idx = int(m)
                    year = int(y)
                    
                    # Compute Month Name
                    months = ["Unknown", "January", "February", "March", "April", "May", "June", 
                              "July", "August", "September", "October", "November", "December"]
                    if 1 <= month_idx <= 12:
                        month_name = months[month_idx]
                    
                    # Compute FY
                    if month_idx >= 4:
                        fy = f"{year}-{str(year+1)[-2:]}"
                    else:
                        fy = f"{year-1}-{str(year)[-2:]}"
                except:
                    pass
            elif fy == '-' and period != '-':
                # Fallback if period is just a name like "January"
                month_name = period
            
            # 2. Other fields
            filed_date = filing.get('filed_date', filing.get('date_of_filing', '-'))
            status = filing.get('status', '-')
            rtn_type = filing.get('return_type', '-')
            
            pdf.cell(40, 8, str(fy), border=1)
            pdf.cell(40, 8, str(month_name), border=1)
            pdf.cell(40, 8, str(rtn_type), border=1)
            pdf.cell(30, 8, str(status), border=1)
            pdf.cell(30, 8, str(filed_date), border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            
    # Disclaimer
    pdf.ln(10)
    pdf.set_font("helvetica", "I", 8)
    pdf.set_text_color(107, 114, 128)
    pdf.multi_cell(CONTENT_WIDTH, 4, "Disclaimer: This certificate is generated based on the GST data available at the time of verification. The compliance status may change based on subsequent filings or government actions. Users are advised to verify critical data directly from the GST portal.")

    return pdf.output()
